### ISSUE TITLE
Forum 

### ISSUE THREAD

**Issue by FadumaD** [AlastairHafield/StuddyBuddy-Project#4]
To be able to chat with student all around the world about a specific topic in each forum. Allowing people to help each other and fix and share codes.

**Comment by AlastairHafield** [comment]
adding ability to add questions
;
*create question table,
column : 
-question 
-id field
-user.id foreign key => user table cascading 
*css

**Comment by AlastairHafield** [comment]
questions (with edit and delete post working), comments working
